apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app-container
          image: my-spring-app:latest
          imagePullPolicy: Never # Critical for local Docker images
          ports:
            - containerPort: 8080